### ISSUE TITLE
Insufficient Funds Error Does Not Display Properly After Publish

### ISSUE THREAD

**Issue by CjMapope** [lbryio/lbry-app#216]
## The Issue
Insufficient funds error does not display properly in pop-up after failed publish
### Steps to reproduce
1. Attempt to publish, setting a fee ABOVE your wallets current balance
2. Pop-up for insufficient balance error appears 
3. Error is apparent, does not actually SAY "Insufficient funds" (but shows in console of course)

### Expected behavior
Error pop-up should have the actual words "Insufficent funds"

### Actual behavior
It does not (see screenshots below)

## System Configuration

Screenshot below

## Anything Else
Noticed by Mac user, confirmed on my own win 10 PC, System config screenshot is for original errors machine

## Screenshots

![error](https://user-images.githubusercontent.com/12862793/26953211-4ebfb708-4c66-11e7-8dd0-58bc3d88cbca.png)
![confirm](https://user-images.githubusercontent.com/12862793/26953217-56ba3c62-4c66-11e7-9637-e8d130a01b6b.PNG)
![config](https://user-images.githubusercontent.com/12862793/26953304-c9802eaa-4c66-11e7-895e-d222bdf4e08b.png)

**Comment by kauffj** [comment]
This is fixed.

**Comment by tzarebczan** [comment]
There is still an issue if you try to leave less than 1 Lbc in the wallet... Can you confirm @CjMapope? A user in #help just had the issue.
